name: Build Status

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - name: Create status badge
        run: echo "Build status updated"
        
      - name: Update README badges
        uses: actions/github-script@v6
        if: github.ref == 'refs/heads/main'
        with:
          script: |
            // Badge URLs
            const buildBadge = `![Build Status](https://github.com/${{ github.repository }}/workflows/CI%20Pipeline/badge.svg)`;
            const deployBadge = `![Deploy Status](https://github.com/${{ github.repository }}/workflows/Deploy%20Pipeline/badge.svg)`;
            const coverageBadge = `![Coverage](https://codecov.io/gh/${{ github.repository }}/branch/main/graph/badge.svg)`;
            
            console.log('Status badges updated');