name: Changelog Generation

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: .github/cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          
      - name: Print changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
        
      - name: Commit changelog
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git diff --cached --quiet || git commit -m "chore: update changelog [skip ci]"
          git push