version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "magicat777"
    reviewers:
      - "magicat777"
    commit-message:
      prefix: "chore"
      include: "scope"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "magicat777"
    reviewers:
      - "magicat777"
    commit-message:
      prefix: "ci"
      include: "scope"